services:
  - type: web
    name: your_service_name
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_uri_here
      - key: PORT
        value: 5000
